// AUTO-GENERATED by scripts/build-cases.mjs — every case verified to have
// exactly one solution and to be solvable without guessing. Do not hand-edit.
export const CAMPAIGN_CASES = [
 {
  "id": "c01",
  "title": "The Gilt Manor Affair",
  "size": 4,
  "roomOf": [
   2,
   2,
   2,
   2,
   2,
   0,
   0,
   0,
   1,
   1,
   1,
   0,
   1,
   1,
   1,
   0
  ],
  "rooms": [
   {
    "name": "Cellar",
    "hue": 0
   },
   {
    "name": "Library",
    "hue": 120
   },
   {
    "name": "Kitchen",
    "hue": 240
   }
  ],
  "furniture": {
   "2": {
    "type": "candelabrum"
   },
   "7": {
    "type": "armchair"
   },
   "9": {
    "type": "clock"
   }
  },
  "people": [
   {
    "id": "vera",
    "name": "Vera Vantablack",
    "role": "the veiled widow",
    "emoji": "🕷️",
    "color": "#8b5cf6"
   },
   {
    "id": "ash",
    "name": "Colonel Ash Redwood",
    "role": "the retired colonel",
    "emoji": "🎖️",
    "color": "#ef4444"
   },
   {
    "id": "felix",
    "name": "Dr. Felix Grimm",
    "role": "the village physician",
    "emoji": "🩺",
    "color": "#10b981"
   },
   {
    "id": "v_gilt",
    "name": "Barnaby Gilt",
    "role": "the millionaire host",
    "emoji": "🎩",
    "isVictim": true,
    "color": "#94a3b8"
   }
  ],
  "clues": [
   {
    "owner": "v_gilt",
    "kind": "dir_of_person",
    "other": "felix",
    "dir": "east"
   },
   {
    "owner": "ash",
    "kind": "same_col_object",
    "objType": "clock"
   },
   {
    "owner": "ash",
    "kind": "dir_of_person",
    "other": "vera",
    "dir": "east"
   },
   {
    "owner": "vera",
    "kind": "dir_of_person",
    "other": "v_gilt",
    "dir": "south"
   },
   {
    "owner": "ash",
    "kind": "edge",
    "dir": "south"
   },
   {
    "owner": "felix",
    "kind": "beside_object",
    "objType": "clock"
   }
  ],
  "givens": {},
  "story": {
   "title": "The Gilt Manor Affair",
   "intro": "Millionaire Barnaby Gilt invited three guests for brandy and bragging. By midnight, only the bragging had stopped — permanently. Reconstruct where everyone stood when the lights went out.",
   "reveal": "Cornered by your flawless map of the manor, {murderer} confessed: the will was to be rewritten at dawn, and {murdererShort} preferred the old arithmetic."
  },
  "theme": {
   "objectNames": {
    "bookshelf": {
     "label": "bookshelf",
     "plural": "bookshelves",
     "emoji": "📚"
    },
    "plant": {
     "label": "potted plant",
     "plural": "potted plants",
     "emoji": "🪴"
    },
    "candelabrum": {
     "label": "candelabrum",
     "plural": "candelabra",
     "emoji": "🕯️"
    },
    "armchair": {
     "label": "armchair",
     "plural": "armchairs",
     "emoji": "🛋️"
    },
    "clock": {
     "label": "grandfather clock",
     "plural": "grandfather clocks",
     "emoji": "🕰️"
    },
    "piano": {
     "label": "piano",
     "plural": "pianos",
     "emoji": "🎹"
    },
    "oven": {
     "label": "oven",
     "plural": "ovens",
     "emoji": "🔥"
    },
    "sack": {
     "label": "flour sack",
     "plural": "flour sacks",
     "emoji": "🌾"
    },
    "cake": {
     "label": "wedding cake",
     "plural": "wedding cakes",
     "emoji": "🎂"
    },
    "telescope": {
     "label": "telescope",
     "plural": "telescopes",
     "emoji": "🔭"
    },
    "globe": {
     "label": "star globe",
     "plural": "star globes",
     "emoji": "🌐"
    },
    "desk": {
     "label": "writing desk",
     "plural": "writing desks",
     "emoji": "🪑"
    },
    "slot": {
     "label": "slot machine",
     "plural": "slot machines",
     "emoji": "🎰"
    },
    "cards": {
     "label": "card table",
     "plural": "card tables",
     "emoji": "🃏"
    },
    "vault": {
     "label": "vault door",
     "plural": "vault doors",
     "emoji": "🔒"
    },
    "harp": {
     "label": "harp",
     "plural": "harps",
     "emoji": "🎻"
    },
    "curtain": {
     "label": "velvet curtain",
     "plural": "velvet curtains",
     "emoji": "🎭"
    },
    "chandelier": {
     "label": "fallen chandelier",
     "plural": "fallen chandeliers",
     "emoji": "💎"
    },
    "crate": {
     "label": "cargo crate",
     "plural": "cargo crates",
     "emoji": "📦"
    },
    "lantern": {
     "label": "storm lantern",
     "plural": "storm lanterns",
     "emoji": "🏮"
    },
    "wheel": {
     "label": "ship's wheel",
     "plural": "ship's wheels",
     "emoji": "☸️"
    },
    "fern": {
     "label": "giant fern",
     "plural": "giant ferns",
     "emoji": "🌿"
    },
    "fountain": {
     "label": "stone fountain",
     "plural": "stone fountains",
     "emoji": "⛲"
    },
    "beehive": {
     "label": "beehive",
     "plural": "beehives",
     "emoji": "🐝"
    },
    "statue": {
     "label": "marble statue",
     "plural": "marble statues",
     "emoji": "🗿"
    },
    "sarcophagus": {
     "label": "sarcophagus",
     "plural": "sarcophagi",
     "emoji": "⚱️"
    },
    "display": {
     "label": "display case",
     "plural": "display cases",
     "emoji": "🏺"
    }
   }
  },
  "solution": {
   "ash": 13,
   "felix": 10,
   "vera": 4,
   "v_gilt": 3
  },
  "murderer": "vera",
  "difficulty": "easy"
 },
 {
  "id": "c02",
  "title": "Death Rises at Dawn",
  "size": 4,
  "roomOf": [
   0,
   2,
   2,
   2,
   0,
   1,
   1,
   2,
   0,
   1,
   1,
   2,
   0,
   1,
   1,
   2
  ],
  "rooms": [
   {
    "name": "Courtyard",
    "hue": 0
   },
   {
    "name": "Bakehouse",
    "hue": 120
   },
   {
    "name": "Pantry",
    "hue": 240
   }
  ],
  "furniture": {
   "1": {
    "type": "oven"
   },
   "8": {
    "type": "cake"
   },
   "10": {
    "type": "sack"
   }
  },
  "people": [
   {
    "id": "basil",
    "name": "Chef Aurelio Basil",
    "role": "the temperamental chef",
    "emoji": "🍳",
    "color": "#f97316"
   },
   {
    "id": "prudence",
    "name": "Lady Prudence Opaline",
    "role": "the jewel heiress",
    "emoji": "💍",
    "color": "#f59e0b"
   },
   {
    "id": "coco",
    "name": "Mademoiselle Coco Lark",
    "role": "the cabaret singer",
    "emoji": "🎤",
    "color": "#ec4899"
   },
   {
    "id": "v_crumb",
    "name": "Otto Crumb",
    "role": "the master baker",
    "emoji": "🥖",
    "isVictim": true,
    "color": "#94a3b8"
   }
  ],
  "clues": [
   {
    "owner": "basil",
    "kind": "in_room",
    "room": 2
   },
   {
    "owner": "coco",
    "kind": "dir_of_person",
    "other": "v_crumb",
    "dir": "west"
   },
   {
    "owner": "prudence",
    "kind": "dir_of_person",
    "other": "coco",
    "dir": "east"
   },
   {
    "owner": "prudence",
    "kind": "dir_of_object",
    "objType": "cake",
    "dir": "south"
   },
   {
    "owner": "v_crumb",
    "kind": "edge",
    "dir": "north"
   }
  ],
  "givens": {},
  "story": {
   "title": "Death Rises at Dawn",
   "intro": "Master baker Otto Crumb was found cold beside his proofing dough — which, unlike him, had risen. Three early visitors were in the bakery. The flour on the floor remembers every step.",
   "reveal": "The flour never lies. {murderer} had traded the shop’s secret starter to a rival — and Otto had found the receipt."
  },
  "theme": {
   "objectNames": {
    "bookshelf": {
     "label": "bookshelf",
     "plural": "bookshelves",
     "emoji": "📚"
    },
    "plant": {
     "label": "potted plant",
     "plural": "potted plants",
     "emoji": "🪴"
    },
    "candelabrum": {
     "label": "candelabrum",
     "plural": "candelabra",
     "emoji": "🕯️"
    },
    "armchair": {
     "label": "armchair",
     "plural": "armchairs",
     "emoji": "🛋️"
    },
    "clock": {
     "label": "grandfather clock",
     "plural": "grandfather clocks",
     "emoji": "🕰️"
    },
    "piano": {
     "label": "piano",
     "plural": "pianos",
     "emoji": "🎹"
    },
    "oven": {
     "label": "oven",
     "plural": "ovens",
     "emoji": "🔥"
    },
    "sack": {
     "label": "flour sack",
     "plural": "flour sacks",
     "emoji": "🌾"
    },
    "cake": {
     "label": "wedding cake",
     "plural": "wedding cakes",
     "emoji": "🎂"
    },
    "telescope": {
     "label": "telescope",
     "plural": "telescopes",
     "emoji": "🔭"
    },
    "globe": {
     "label": "star globe",
     "plural": "star globes",
     "emoji": "🌐"
    },
    "desk": {
     "label": "writing desk",
     "plural": "writing desks",
     "emoji": "🪑"
    },
    "slot": {
     "label": "slot machine",
     "plural": "slot machines",
     "emoji": "🎰"
    },
    "cards": {
     "label": "card table",
     "plural": "card tables",
     "emoji": "🃏"
    },
    "vault": {
     "label": "vault door",
     "plural": "vault doors",
     "emoji": "🔒"
    },
    "harp": {
     "label": "harp",
     "plural": "harps",
     "emoji": "🎻"
    },
    "curtain": {
     "label": "velvet curtain",
     "plural": "velvet curtains",
     "emoji": "🎭"
    },
    "chandelier": {
     "label": "fallen chandelier",
     "plural": "fallen chandeliers",
     "emoji": "💎"
    },
    "crate": {
     "label": "cargo crate",
     "plural": "cargo crates",
     "emoji": "📦"
    },
    "lantern": {
     "label": "storm lantern",
     "plural": "storm lanterns",
     "emoji": "🏮"
    },
    "wheel": {
     "label": "ship's wheel",
     "plural": "ship's wheels",
     "emoji": "☸️"
    },
    "fern": {
     "label": "giant fern",
     "plural": "giant ferns",
     "emoji": "🌿"
    },
    "fountain": {
     "label": "stone fountain",
     "plural": "stone fountains",
     "emoji": "⛲"
    },
    "beehive": {
     "label": "beehive",
     "plural": "beehives",
     "emoji": "🐝"
    },
    "statue": {
     "label": "marble statue",
     "plural": "marble statues",
     "emoji": "🗿"
    },
    "sarcophagus": {
     "label": "sarcophagus",
     "plural": "sarcophagi",
     "emoji": "⚱️"
    },
    "display": {
     "label": "display case",
     "plural": "display cases",
     "emoji": "🏺"
    }
   }
  },
  "solution": {
   "v_crumb": 2,
   "prudence": 13,
   "basil": 11,
   "coco": 4
  },
  "murderer": "basil",
  "difficulty": "easy"
 },
 {
  "id": "c03",
  "title": "The Comet That Never Came",
  "size": 5,
  "roomOf": [
   2,
   2,
   2,
   2,
   2,
   0,
   0,
   0,
   2,
   1,
   0,
   0,
   0,
   1,
   1,
   3,
   3,
   3,
   1,
   1,
   3,
   3,
   3,
   1,
   1
  ],
  "rooms": [
   {
    "name": "Chart Room",
    "hue": 0
   },
   {
    "name": "Workshop",
    "hue": 90
   },
   {
    "name": "Stairwell",
    "hue": 180
   },
   {
    "name": "Archive",
    "hue": 270
   }
  ],
  "furniture": {
   "7": {
    "type": "telescope"
   },
   "10": {
    "type": "lantern"
   },
   "19": {
    "type": "telescope"
   },
   "24": {
    "type": "globe"
   }
  },
  "people": [
   {
    "id": "wren",
    "name": "Professor Thaddeus Wren",
    "role": "the absent-minded professor",
    "emoji": "🦉",
    "color": "#14b8a6"
   },
   {
    "id": "vera",
    "name": "Vera Vantablack",
    "role": "the veiled widow",
    "emoji": "🕷️",
    "color": "#8b5cf6"
   },
   {
    "id": "indigo",
    "name": "Captain Indigo Marsh",
    "role": "the storm-worn captain",
    "emoji": "⚓",
    "color": "#3b82f6"
   },
   {
    "id": "felix",
    "name": "Dr. Felix Grimm",
    "role": "the village physician",
    "emoji": "🩺",
    "color": "#10b981"
   },
   {
    "id": "v_starr",
    "name": "Dr. Celeste Starr",
    "role": "the royal astronomer",
    "emoji": "🌠",
    "isVictim": true,
    "color": "#94a3b8"
   }
  ],
  "clues": [
   {
    "owner": "felix",
    "kind": "edge",
    "dir": "west"
   },
   {
    "owner": "felix",
    "kind": "beside_object",
    "objType": "lantern"
   },
   {
    "owner": "vera",
    "kind": "dir_of_person",
    "other": "wren",
    "dir": "south"
   },
   {
    "owner": "vera",
    "kind": "dir_of_person",
    "other": "wren",
    "dir": "east"
   },
   {
    "owner": "wren",
    "kind": "dir_of_person",
    "other": "v_starr",
    "dir": "east"
   },
   {
    "owner": "indigo",
    "kind": "same_col_object",
    "objType": "telescope"
   },
   {
    "owner": "indigo",
    "kind": "same_row_object",
    "objType": "telescope"
   },
   {
    "owner": "v_starr",
    "kind": "dir_of_person",
    "other": "vera",
    "dir": "west"
   }
  ],
  "givens": {},
  "story": {
   "title": "The Comet That Never Came",
   "intro": "Dr. Celeste Starr promised the town a comet at 11:07. At 11:08 she was dead under her own dome. Four colleagues were inside when the shutters jammed.",
   "reveal": "Your chart of the observatory left no shadow to hide in. {murderer} had faked the comet data for funding — and Celeste was about to publish the truth."
  },
  "theme": {
   "objectNames": {
    "bookshelf": {
     "label": "bookshelf",
     "plural": "bookshelves",
     "emoji": "📚"
    },
    "plant": {
     "label": "potted plant",
     "plural": "potted plants",
     "emoji": "🪴"
    },
    "candelabrum": {
     "label": "candelabrum",
     "plural": "candelabra",
     "emoji": "🕯️"
    },
    "armchair": {
     "label": "armchair",
     "plural": "armchairs",
     "emoji": "🛋️"
    },
    "clock": {
     "label": "grandfather clock",
     "plural": "grandfather clocks",
     "emoji": "🕰️"
    },
    "piano": {
     "label": "piano",
     "plural": "pianos",
     "emoji": "🎹"
    },
    "oven": {
     "label": "oven",
     "plural": "ovens",
     "emoji": "🔥"
    },
    "sack": {
     "label": "flour sack",
     "plural": "flour sacks",
     "emoji": "🌾"
    },
    "cake": {
     "label": "wedding cake",
     "plural": "wedding cakes",
     "emoji": "🎂"
    },
    "telescope": {
     "label": "telescope",
     "plural": "telescopes",
     "emoji": "🔭"
    },
    "globe": {
     "label": "star globe",
     "plural": "star globes",
     "emoji": "🌐"
    },
    "desk": {
     "label": "writing desk",
     "plural": "writing desks",
     "emoji": "🪑"
    },
    "slot": {
     "label": "slot machine",
     "plural": "slot machines",
     "emoji": "🎰"
    },
    "cards": {
     "label": "card table",
     "plural": "card tables",
     "emoji": "🃏"
    },
    "vault": {
     "label": "vault door",
     "plural": "vault doors",
     "emoji": "🔒"
    },
    "harp": {
     "label": "harp",
     "plural": "harps",
     "emoji": "🎻"
    },
    "curtain": {
     "label": "velvet curtain",
     "plural": "velvet curtains",
     "emoji": "🎭"
    },
    "chandelier": {
     "label": "fallen chandelier",
     "plural": "fallen chandeliers",
     "emoji": "💎"
    },
    "crate": {
     "label": "cargo crate",
     "plural": "cargo crates",
     "emoji": "📦"
    },
    "lantern": {
     "label": "storm lantern",
     "plural": "storm lanterns",
     "emoji": "🏮"
    },
    "wheel": {
     "label": "ship's wheel",
     "plural": "ship's wheels",
     "emoji": "☸️"
    },
    "fern": {
     "label": "giant fern",
     "plural": "giant ferns",
     "emoji": "🌿"
    },
    "fountain": {
     "label": "stone fountain",
     "plural": "stone fountains",
     "emoji": "⛲"
    },
    "beehive": {
     "label": "beehive",
     "plural": "beehives",
     "emoji": "🐝"
    },
    "statue": {
     "label": "marble statue",
     "plural": "marble statues",
     "emoji": "🗿"
    },
    "sarcophagus": {
     "label": "sarcophagus",
     "plural": "sarcophagi",
     "emoji": "⚱️"
    },
    "display": {
     "label": "display case",
     "plural": "display cases",
     "emoji": "🏺"
    }
   }
  },
  "solution": {
   "felix": 5,
   "indigo": 17,
   "wren": 3,
   "vera": 14,
   "v_starr": 21
  },
  "murderer": "indigo",
  "difficulty": "easy"
 },
 {
  "id": "c04",
  "title": "Snake Eyes at the Silver Slipper",
  "size": 5,
  "roomOf": [
   3,
   3,
   3,
   2,
   2,
   0,
   3,
   3,
   2,
   2,
   0,
   0,
   0,
   1,
   2,
   0,
   1,
   1,
   1,
   2,
   0,
   1,
   1,
   1,
   2
  ],
  "rooms": [
   {
    "name": "Back Office",
    "hue": 0
   },
   {
    "name": "Gaming Floor",
    "hue": 90
   },
   {
    "name": "Terrace",
    "hue": 180
   },
   {
    "name": "Lounge",
    "hue": 270
   }
  ],
  "furniture": {
   "2": {
    "type": "cards"
   },
   "9": {
    "type": "slot"
   },
   "10": {
    "type": "plant"
   },
   "20": {
    "type": "slot"
   }
  },
  "people": [
   {
    "id": "prudence",
    "name": "Lady Prudence Opaline",
    "role": "the jewel heiress",
    "emoji": "💍",
    "color": "#f59e0b"
   },
   {
    "id": "ash",
    "name": "Colonel Ash Redwood",
    "role": "the retired colonel",
    "emoji": "🎖️",
    "color": "#ef4444"
   },
   {
    "id": "coco",
    "name": "Mademoiselle Coco Lark",
    "role": "the cabaret singer",
    "emoji": "🎤",
    "color": "#ec4899"
   },
   {
    "id": "basil",
    "name": "Chef Aurelio Basil",
    "role": "the temperamental chef",
    "emoji": "🍳",
    "color": "#f97316"
   },
   {
    "id": "v_marlow",
    "name": "Sonny Marlow",
    "role": "the pit boss",
    "emoji": "🎲",
    "isVictim": true,
    "color": "#94a3b8"
   }
  ],
  "clues": [
   {
    "owner": "ash",
    "kind": "dir_of_person",
    "other": "coco",
    "dir": "south"
   },
   {
    "owner": "prudence",
    "kind": "not_beside_object",
    "objType": "cards"
   },
   {
    "owner": "coco",
    "kind": "dir_of_person",
    "other": "v_marlow",
    "dir": "east"
   },
   {
    "owner": "v_marlow",
    "kind": "dir_of_object",
    "objType": "cards",
    "dir": "east"
   },
   {
    "owner": "basil",
    "kind": "beside_object",
    "objType": "cards"
   },
   {
    "owner": "prudence",
    "kind": "dir_of_person",
    "other": "basil",
    "dir": "east"
   }
  ],
  "givens": {},
  "story": {
   "title": "Snake Eyes at the Silver Slipper",
   "intro": "Pit boss Sonny Marlow always said the house never loses. Tonight the house lost him. Four patrons were still on the floor when the chips stopped clicking.",
   "reveal": "The odds finally caught up. {murderer} owed the Silver Slipper more than money — and Sonny had started collecting in secrets."
  },
  "theme": {
   "objectNames": {
    "bookshelf": {
     "label": "bookshelf",
     "plural": "bookshelves",
     "emoji": "📚"
    },
    "plant": {
     "label": "potted plant",
     "plural": "potted plants",
     "emoji": "🪴"
    },
    "candelabrum": {
     "label": "candelabrum",
     "plural": "candelabra",
     "emoji": "🕯️"
    },
    "armchair": {
     "label": "armchair",
     "plural": "armchairs",
     "emoji": "🛋️"
    },
    "clock": {
     "label": "grandfather clock",
     "plural": "grandfather clocks",
     "emoji": "🕰️"
    },
    "piano": {
     "label": "piano",
     "plural": "pianos",
     "emoji": "🎹"
    },
    "oven": {
     "label": "oven",
     "plural": "ovens",
     "emoji": "🔥"
    },
    "sack": {
     "label": "flour sack",
     "plural": "flour sacks",
     "emoji": "🌾"
    },
    "cake": {
     "label": "wedding cake",
     "plural": "wedding cakes",
     "emoji": "🎂"
    },
    "telescope": {
     "label": "telescope",
     "plural": "telescopes",
     "emoji": "🔭"
    },
    "globe": {
     "label": "star globe",
     "plural": "star globes",
     "emoji": "🌐"
    },
    "desk": {
     "label": "writing desk",
     "plural": "writing desks",
     "emoji": "🪑"
    },
    "slot": {
     "label": "slot machine",
     "plural": "slot machines",
     "emoji": "🎰"
    },
    "cards": {
     "label": "card table",
     "plural": "card tables",
     "emoji": "🃏"
    },
    "vault": {
     "label": "vault door",
     "plural": "vault doors",
     "emoji": "🔒"
    },
    "harp": {
     "label": "harp",
     "plural": "harps",
     "emoji": "🎻"
    },
    "curtain": {
     "label": "velvet curtain",
     "plural": "velvet curtains",
     "emoji": "🎭"
    },
    "chandelier": {
     "label": "fallen chandelier",
     "plural": "fallen chandeliers",
     "emoji": "💎"
    },
    "crate": {
     "label": "cargo crate",
     "plural": "cargo crates",
     "emoji": "📦"
    },
    "lantern": {
     "label": "storm lantern",
     "plural": "storm lanterns",
     "emoji": "🏮"
    },
    "wheel": {
     "label": "ship's wheel",
     "plural": "ship's wheels",
     "emoji": "☸️"
    },
    "fern": {
     "label": "giant fern",
     "plural": "giant ferns",
     "emoji": "🌿"
    },
    "fountain": {
     "label": "stone fountain",
     "plural": "stone fountains",
     "emoji": "⛲"
    },
    "beehive": {
     "label": "beehive",
     "plural": "beehives",
     "emoji": "🐝"
    },
    "statue": {
     "label": "marble statue",
     "plural": "marble statues",
     "emoji": "🗿"
    },
    "sarcophagus": {
     "label": "sarcophagus",
     "plural": "sarcophagi",
     "emoji": "⚱️"
    },
    "display": {
     "label": "display case",
     "plural": "display cases",
     "emoji": "🏺"
    }
   }
  },
  "solution": {
   "basil": 1,
   "v_marlow": 8,
   "prudence": 22,
   "ash": 15,
   "coco": 14
  },
  "murderer": "coco",
  "difficulty": "medium"
 },
 {
  "id": "c05",
  "title": "Aria for a Dead Maestro",
  "size": 6,
  "roomOf": [
   1,
   1,
   2,
   2,
   2,
   2,
   1,
   1,
   0,
   0,
   2,
   2,
   1,
   1,
   0,
   0,
   0,
   2,
   1,
   0,
   0,
   0,
   4,
   2,
   1,
   1,
   3,
   4,
   4,
   4,
   3,
   3,
   3,
   4,
   4,
   4
  ],
  "rooms": [
   {
    "name": "Orchestra Pit",
    "hue": 0
   },
   {
    "name": "Foyer",
    "hue": 72
   },
   {
    "name": "Stage",
    "hue": 144
   },
   {
    "name": "Dressing Room",
    "hue": 216
   },
   {
    "name": "Fly Tower",
    "hue": 288
   }
  ],
  "furniture": {
   "1": {
    "type": "piano"
   },
   "5": {
    "type": "harp"
   },
   "12": {
    "type": "harp"
   },
   "23": {
    "type": "candelabrum"
   },
   "26": {
    "type": "chandelier"
   },
   "27": {
    "type": "candelabrum"
   }
  },
  "people": [
   {
    "id": "coco",
    "name": "Mademoiselle Coco Lark",
    "role": "the cabaret singer",
    "emoji": "🎤",
    "color": "#ec4899"
   },
   {
    "id": "vera",
    "name": "Vera Vantablack",
    "role": "the veiled widow",
    "emoji": "🕷️",
    "color": "#8b5cf6"
   },
   {
    "id": "wren",
    "name": "Professor Thaddeus Wren",
    "role": "the absent-minded professor",
    "emoji": "🦉",
    "color": "#14b8a6"
   },
   {
    "id": "prudence",
    "name": "Lady Prudence Opaline",
    "role": "the jewel heiress",
    "emoji": "💍",
    "color": "#f59e0b"
   },
   {
    "id": "indigo",
    "name": "Captain Indigo Marsh",
    "role": "the storm-worn captain",
    "emoji": "⚓",
    "color": "#3b82f6"
   },
   {
    "id": "v_fontaine",
    "name": "Maestro Rex Fontaine",
    "role": "the tyrant conductor",
    "emoji": "🎼",
    "isVictim": true,
    "color": "#94a3b8"
   }
  ],
  "clues": [
   {
    "owner": "v_fontaine",
    "kind": "not_beside_object",
    "objType": "candelabrum"
   },
   {
    "owner": "vera",
    "kind": "dir_of_object",
    "objType": "piano",
    "dir": "west"
   },
   {
    "owner": "wren",
    "kind": "dir_of_person",
    "other": "v_fontaine",
    "dir": "north"
   },
   {
    "owner": "indigo",
    "kind": "in_room",
    "room": 4
   },
   {
    "owner": "prudence",
    "kind": "not_same_room_person",
    "other": "indigo"
   },
   {
    "owner": "coco",
    "kind": "not_same_room_person",
    "other": "v_fontaine"
   },
   {
    "owner": "v_fontaine",
    "kind": "dir_of_person",
    "other": "indigo",
    "dir": "east"
   },
   {
    "owner": "coco",
    "kind": "dir_of_person",
    "other": "indigo",
    "dir": "south"
   },
   {
    "owner": "wren",
    "kind": "beside_object",
    "objType": "harp"
   },
   {
    "owner": "vera",
    "kind": "same_row_object",
    "objType": "piano"
   }
  ],
  "givens": {},
  "story": {
   "title": "Aria for a Dead Maestro",
   "intro": "Maestro Rex Fontaine cut the soprano’s solo one time too many. During the blackout of Act II, someone cut his. Five members of the company never left the house.",
   "reveal": "Bravo! With the stage mapped to the inch, {murderer} broke down in the wings: Fontaine had threatened to end a career tonight — instead, someone ended his encore."
  },
  "theme": {
   "objectNames": {
    "bookshelf": {
     "label": "bookshelf",
     "plural": "bookshelves",
     "emoji": "📚"
    },
    "plant": {
     "label": "potted plant",
     "plural": "potted plants",
     "emoji": "🪴"
    },
    "candelabrum": {
     "label": "candelabrum",
     "plural": "candelabra",
     "emoji": "🕯️"
    },
    "armchair": {
     "label": "armchair",
     "plural": "armchairs",
     "emoji": "🛋️"
    },
    "clock": {
     "label": "grandfather clock",
     "plural": "grandfather clocks",
     "emoji": "🕰️"
    },
    "piano": {
     "label": "piano",
     "plural": "pianos",
     "emoji": "🎹"
    },
    "oven": {
     "label": "oven",
     "plural": "ovens",
     "emoji": "🔥"
    },
    "sack": {
     "label": "flour sack",
     "plural": "flour sacks",
     "emoji": "🌾"
    },
    "cake": {
     "label": "wedding cake",
     "plural": "wedding cakes",
     "emoji": "🎂"
    },
    "telescope": {
     "label": "telescope",
     "plural": "telescopes",
     "emoji": "🔭"
    },
    "globe": {
     "label": "star globe",
     "plural": "star globes",
     "emoji": "🌐"
    },
    "desk": {
     "label": "writing desk",
     "plural": "writing desks",
     "emoji": "🪑"
    },
    "slot": {
     "label": "slot machine",
     "plural": "slot machines",
     "emoji": "🎰"
    },
    "cards": {
     "label": "card table",
     "plural": "card tables",
     "emoji": "🃏"
    },
    "vault": {
     "label": "vault door",
     "plural": "vault doors",
     "emoji": "🔒"
    },
    "harp": {
     "label": "harp",
     "plural": "harps",
     "emoji": "🎻"
    },
    "curtain": {
     "label": "velvet curtain",
     "plural": "velvet curtains",
     "emoji": "🎭"
    },
    "chandelier": {
     "label": "fallen chandelier",
     "plural": "fallen chandeliers",
     "emoji": "💎"
    },
    "crate": {
     "label": "cargo crate",
     "plural": "cargo crates",
     "emoji": "📦"
    },
    "lantern": {
     "label": "storm lantern",
     "plural": "storm lanterns",
     "emoji": "🏮"
    },
    "wheel": {
     "label": "ship's wheel",
     "plural": "ship's wheels",
     "emoji": "☸️"
    },
    "fern": {
     "label": "giant fern",
     "plural": "giant ferns",
     "emoji": "🌿"
    },
    "fountain": {
     "label": "stone fountain",
     "plural": "stone fountains",
     "emoji": "⛲"
    },
    "beehive": {
     "label": "beehive",
     "plural": "beehives",
     "emoji": "🐝"
    },
    "statue": {
     "label": "marble statue",
     "plural": "marble statues",
     "emoji": "🗿"
    },
    "sarcophagus": {
     "label": "sarcophagus",
     "plural": "sarcophagi",
     "emoji": "⚱️"
    },
    "display": {
     "label": "display case",
     "plural": "display cases",
     "emoji": "🏺"
    }
   }
  },
  "solution": {
   "vera": 0,
   "wren": 13,
   "indigo": 22,
   "v_fontaine": 29,
   "coco": 32,
   "prudence": 9
  },
  "murderer": "indigo",
  "difficulty": "medium"
 },
 {
  "id": "c06",
  "title": "Last Voyage of the SS Meridian",
  "size": 6,
  "roomOf": [
   1,
   1,
   1,
   1,
   4,
   4,
   1,
   1,
   1,
   2,
   4,
   4,
   0,
   0,
   0,
   2,
   2,
   2,
   0,
   0,
   0,
   0,
   2,
   2,
   0,
   3,
   3,
   3,
   3,
   2,
   0,
   3,
   3,
   3,
   3,
   2
  ],
  "rooms": [
   {
    "name": "Engine Room",
    "hue": 0
   },
   {
    "name": "Promenade",
    "hue": 72
   },
   {
    "name": "Salon",
    "hue": 144
   },
   {
    "name": "Bridge",
    "hue": 216
   },
   {
    "name": "Cargo Hold",
    "hue": 288
   }
  ],
  "furniture": {
   "0": {
    "type": "lantern"
   },
   "1": {
    "type": "crate"
   },
   "4": {
    "type": "lantern"
   },
   "8": {
    "type": "armchair"
   },
   "20": {
    "type": "armchair"
   },
   "25": {
    "type": "crate"
   }
  },
  "people": [
   {
    "id": "indigo",
    "name": "Captain Indigo Marsh",
    "role": "the storm-worn captain",
    "emoji": "⚓",
    "color": "#3b82f6"
   },
   {
    "id": "felix",
    "name": "Dr. Felix Grimm",
    "role": "the village physician",
    "emoji": "🩺",
    "color": "#10b981"
   },
   {
    "id": "ash",
    "name": "Colonel Ash Redwood",
    "role": "the retired colonel",
    "emoji": "🎖️",
    "color": "#ef4444"
   },
   {
    "id": "coco",
    "name": "Mademoiselle Coco Lark",
    "role": "the cabaret singer",
    "emoji": "🎤",
    "color": "#ec4899"
   },
   {
    "id": "basil",
    "name": "Chef Aurelio Basil",
    "role": "the temperamental chef",
    "emoji": "🍳",
    "color": "#f97316"
   },
   {
    "id": "v_pemberly",
    "name": "Ambassador Iris Pemberly",
    "role": "the retiring diplomat",
    "emoji": "🕊️",
    "isVictim": true,
    "color": "#94a3b8"
   }
  ],
  "clues": [
   {
    "owner": "felix",
    "kind": "dir_of_person",
    "other": "coco",
    "dir": "south"
   },
   {
    "owner": "ash",
    "kind": "in_room",
    "room": 1
   },
   {
    "owner": "v_pemberly",
    "kind": "dir_of_object",
    "objType": "armchair",
    "dir": "west"
   },
   {
    "owner": "v_pemberly",
    "kind": "dir_of_person",
    "other": "basil",
    "dir": "north"
   },
   {
    "owner": "indigo",
    "kind": "dir_of_person",
    "other": "felix",
    "dir": "north"
   },
   {
    "owner": "basil",
    "kind": "same_col_object",
    "objType": "lantern"
   },
   {
    "owner": "coco",
    "kind": "not_in_room",
    "room": 2
   },
   {
    "owner": "v_pemberly",
    "kind": "dir_of_person",
    "other": "felix",
    "dir": "south"
   },
   {
    "owner": "coco",
    "kind": "same_row_object",
    "objType": "armchair"
   },
   {
    "owner": "indigo",
    "kind": "dir_of_person",
    "other": "basil",
    "dir": "east"
   }
  ],
  "givens": {},
  "story": {
   "title": "Last Voyage of the SS Meridian",
   "intro": "Ambassador Iris Pemberly boarded the SS Meridian with a briefcase she never let go. Somewhere between the fog and the foghorn, she let go. Five passengers know exactly where they stood.",
   "reveal": "The briefcase held names — one of them {murderer}’s. The ambassador’s memoirs will now be published posthumously, with one chapter written by you."
  },
  "theme": {
   "objectNames": {
    "bookshelf": {
     "label": "bookshelf",
     "plural": "bookshelves",
     "emoji": "📚"
    },
    "plant": {
     "label": "potted plant",
     "plural": "potted plants",
     "emoji": "🪴"
    },
    "candelabrum": {
     "label": "candelabrum",
     "plural": "candelabra",
     "emoji": "🕯️"
    },
    "armchair": {
     "label": "armchair",
     "plural": "armchairs",
     "emoji": "🛋️"
    },
    "clock": {
     "label": "grandfather clock",
     "plural": "grandfather clocks",
     "emoji": "🕰️"
    },
    "piano": {
     "label": "piano",
     "plural": "pianos",
     "emoji": "🎹"
    },
    "oven": {
     "label": "oven",
     "plural": "ovens",
     "emoji": "🔥"
    },
    "sack": {
     "label": "flour sack",
     "plural": "flour sacks",
     "emoji": "🌾"
    },
    "cake": {
     "label": "wedding cake",
     "plural": "wedding cakes",
     "emoji": "🎂"
    },
    "telescope": {
     "label": "telescope",
     "plural": "telescopes",
     "emoji": "🔭"
    },
    "globe": {
     "label": "star globe",
     "plural": "star globes",
     "emoji": "🌐"
    },
    "desk": {
     "label": "writing desk",
     "plural": "writing desks",
     "emoji": "🪑"
    },
    "slot": {
     "label": "slot machine",
     "plural": "slot machines",
     "emoji": "🎰"
    },
    "cards": {
     "label": "card table",
     "plural": "card tables",
     "emoji": "🃏"
    },
    "vault": {
     "label": "vault door",
     "plural": "vault doors",
     "emoji": "🔒"
    },
    "harp": {
     "label": "harp",
     "plural": "harps",
     "emoji": "🎻"
    },
    "curtain": {
     "label": "velvet curtain",
     "plural": "velvet curtains",
     "emoji": "🎭"
    },
    "chandelier": {
     "label": "fallen chandelier",
     "plural": "fallen chandeliers",
     "emoji": "💎"
    },
    "crate": {
     "label": "cargo crate",
     "plural": "cargo crates",
     "emoji": "📦"
    },
    "lantern": {
     "label": "storm lantern",
     "plural": "storm lanterns",
     "emoji": "🏮"
    },
    "wheel": {
     "label": "ship's wheel",
     "plural": "ship's wheels",
     "emoji": "☸️"
    },
    "fern": {
     "label": "giant fern",
     "plural": "giant ferns",
     "emoji": "🌿"
    },
    "fountain": {
     "label": "stone fountain",
     "plural": "stone fountains",
     "emoji": "⛲"
    },
    "beehive": {
     "label": "beehive",
     "plural": "beehives",
     "emoji": "🐝"
    },
    "statue": {
     "label": "marble statue",
     "plural": "marble statues",
     "emoji": "🗿"
    },
    "sarcophagus": {
     "label": "sarcophagus",
     "plural": "sarcophagi",
     "emoji": "⚱️"
    },
    "display": {
     "label": "display case",
     "plural": "display cases",
     "emoji": "🏺"
    }
   }
  },
  "solution": {
   "ash": 2,
   "coco": 7,
   "v_pemberly": 24,
   "basil": 34,
   "indigo": 17,
   "felix": 21
  },
  "murderer": "felix",
  "difficulty": "medium"
 },
 {
  "id": "c07",
  "title": "The Thorn Garden Party",
  "size": 7,
  "roomOf": [
   3,
   3,
   3,
   2,
   2,
   0,
   0,
   3,
   3,
   2,
   2,
   2,
   2,
   0,
   3,
   3,
   4,
   2,
   1,
   2,
   0,
   3,
   4,
   4,
   1,
   1,
   1,
   0,
   4,
   4,
   4,
   1,
   1,
   0,
   0,
   4,
   4,
   4,
   1,
   1,
   0,
   0,
   4,
   4,
   1,
   1,
   1,
   0,
   0
  ],
  "rooms": [
   {
    "name": "Apiary",
    "hue": 0
   },
   {
    "name": "Gazebo",
    "hue": 72
   },
   {
    "name": "Rose Maze",
    "hue": 144
   },
   {
    "name": "Orchard",
    "hue": 216
   },
   {
    "name": "Greenhouse",
    "hue": 288
   }
  ],
  "furniture": {
   "6": {
    "type": "beehive"
   },
   "15": {
    "type": "fern"
   },
   "19": {
    "type": "beehive"
   },
   "21": {
    "type": "statue"
   },
   "25": {
    "type": "beehive"
   },
   "26": {
    "type": "fountain"
   },
   "40": {
    "type": "fountain"
   },
   "41": {
    "type": "fern"
   }
  },
  "people": [
   {
    "id": "vera",
    "name": "Vera Vantablack",
    "role": "the veiled widow",
    "emoji": "🕷️",
    "color": "#8b5cf6"
   },
   {
    "id": "prudence",
    "name": "Lady Prudence Opaline",
    "role": "the jewel heiress",
    "emoji": "💍",
    "color": "#f59e0b"
   },
   {
    "id": "wren",
    "name": "Professor Thaddeus Wren",
    "role": "the absent-minded professor",
    "emoji": "🦉",
    "color": "#14b8a6"
   },
   {
    "id": "basil",
    "name": "Chef Aurelio Basil",
    "role": "the temperamental chef",
    "emoji": "🍳",
    "color": "#f97316"
   },
   {
    "id": "felix",
    "name": "Dr. Felix Grimm",
    "role": "the village physician",
    "emoji": "🩺",
    "color": "#10b981"
   },
   {
    "id": "indigo",
    "name": "Captain Indigo Marsh",
    "role": "the storm-worn captain",
    "emoji": "⚓",
    "color": "#3b82f6"
   },
   {
    "id": "v_thorn",
    "name": "Sir Digby Thorn",
    "role": "the prize horticulturist",
    "emoji": "🌹",
    "isVictim": true,
    "color": "#94a3b8"
   }
  ],
  "clues": [
   {
    "owner": "prudence",
    "kind": "dir_of_person",
    "other": "indigo",
    "dir": "east"
   },
   {
    "owner": "wren",
    "kind": "edge",
    "dir": "south"
   },
   {
    "owner": "vera",
    "kind": "alone"
   },
   {
    "owner": "wren",
    "kind": "dir_of_object",
    "objType": "fern",
    "dir": "west"
   },
   {
    "owner": "felix",
    "kind": "in_room",
    "room": 1
   },
   {
    "owner": "basil",
    "kind": "alone"
   },
   {
    "owner": "basil",
    "kind": "dir_of_person",
    "other": "felix",
    "dir": "south"
   },
   {
    "owner": "v_thorn",
    "kind": "not_same_room_person",
    "other": "prudence"
   },
   {
    "owner": "indigo",
    "kind": "dir_of_person",
    "other": "felix",
    "dir": "south"
   },
   {
    "owner": "indigo",
    "kind": "dir_of_person",
    "other": "felix",
    "dir": "east"
   }
  ],
  "givens": {},
  "story": {
   "title": "The Thorn Garden Party",
   "intro": "Sir Digby Thorn unveiled his black rose to six guests at the summer party. By teatime the rose was gone and so was Sir Digby. The hedges saw everything. So did you.",
   "reveal": "Pruned at last. {murderer} had crossbred the black rose from a stolen cutting — Sir Digby’s unveiling speech was about to name the thief."
  },
  "theme": {
   "objectNames": {
    "bookshelf": {
     "label": "bookshelf",
     "plural": "bookshelves",
     "emoji": "📚"
    },
    "plant": {
     "label": "potted plant",
     "plural": "potted plants",
     "emoji": "🪴"
    },
    "candelabrum": {
     "label": "candelabrum",
     "plural": "candelabra",
     "emoji": "🕯️"
    },
    "armchair": {
     "label": "armchair",
     "plural": "armchairs",
     "emoji": "🛋️"
    },
    "clock": {
     "label": "grandfather clock",
     "plural": "grandfather clocks",
     "emoji": "🕰️"
    },
    "piano": {
     "label": "piano",
     "plural": "pianos",
     "emoji": "🎹"
    },
    "oven": {
     "label": "oven",
     "plural": "ovens",
     "emoji": "🔥"
    },
    "sack": {
     "label": "flour sack",
     "plural": "flour sacks",
     "emoji": "🌾"
    },
    "cake": {
     "label": "wedding cake",
     "plural": "wedding cakes",
     "emoji": "🎂"
    },
    "telescope": {
     "label": "telescope",
     "plural": "telescopes",
     "emoji": "🔭"
    },
    "globe": {
     "label": "star globe",
     "plural": "star globes",
     "emoji": "🌐"
    },
    "desk": {
     "label": "writing desk",
     "plural": "writing desks",
     "emoji": "🪑"
    },
    "slot": {
     "label": "slot machine",
     "plural": "slot machines",
     "emoji": "🎰"
    },
    "cards": {
     "label": "card table",
     "plural": "card tables",
     "emoji": "🃏"
    },
    "vault": {
     "label": "vault door",
     "plural": "vault doors",
     "emoji": "🔒"
    },
    "harp": {
     "label": "harp",
     "plural": "harps",
     "emoji": "🎻"
    },
    "curtain": {
     "label": "velvet curtain",
     "plural": "velvet curtains",
     "emoji": "🎭"
    },
    "chandelier": {
     "label": "fallen chandelier",
     "plural": "fallen chandeliers",
     "emoji": "💎"
    },
    "crate": {
     "label": "cargo crate",
     "plural": "cargo crates",
     "emoji": "📦"
    },
    "lantern": {
     "label": "storm lantern",
     "plural": "storm lanterns",
     "emoji": "🏮"
    },
    "wheel": {
     "label": "ship's wheel",
     "plural": "ship's wheels",
     "emoji": "☸️"
    },
    "fern": {
     "label": "giant fern",
     "plural": "giant ferns",
     "emoji": "🌿"
    },
    "fountain": {
     "label": "stone fountain",
     "plural": "stone fountains",
     "emoji": "⛲"
    },
    "beehive": {
     "label": "beehive",
     "plural": "beehives",
     "emoji": "🐝"
    },
    "statue": {
     "label": "marble statue",
     "plural": "marble statues",
     "emoji": "🗿"
    },
    "sarcophagus": {
     "label": "sarcophagus",
     "plural": "sarcophagi",
     "emoji": "⚱️"
    },
    "display": {
     "label": "display case",
     "plural": "display cases",
     "emoji": "🏺"
    }
   }
  },
  "solution": {
   "wren": 42,
   "felix": 24,
   "vera": 1,
   "prudence": 12,
   "basil": 34,
   "indigo": 39,
   "v_thorn": 16
  },
  "murderer": "wren",
  "difficulty": "hard"
 },
 {
  "id": "c08",
  "title": "Midnight at the Meridian Museum",
  "size": 7,
  "roomOf": [
   0,
   4,
   2,
   2,
   2,
   2,
   2,
   0,
   4,
   4,
   2,
   2,
   2,
   2,
   0,
   4,
   4,
   1,
   1,
   1,
   2,
   0,
   4,
   4,
   1,
   1,
   1,
   1,
   0,
   4,
   4,
   1,
   1,
   1,
   1,
   0,
   0,
   3,
   3,
   3,
   3,
   3,
   0,
   0,
   0,
   3,
   3,
   3,
   3
  ],
  "rooms": [
   {
    "name": "Curator Office",
    "hue": 0
   },
   {
    "name": "Rotunda",
    "hue": 72
   },
   {
    "name": "Grand Hall",
    "hue": 144
   },
   {
    "name": "Egyptian Wing",
    "hue": 216
   },
   {
    "name": "Vault",
    "hue": 288
   }
  ],
  "furniture": {
   "22": {
    "type": "bookshelf"
   },
   "24": {
    "type": "candelabrum"
   },
   "25": {
    "type": "candelabrum"
   },
   "30": {
    "type": "sarcophagus"
   },
   "31": {
    "type": "candelabrum"
   },
   "34": {
    "type": "sarcophagus"
   },
   "35": {
    "type": "statue"
   },
   "36": {
    "type": "candelabrum"
   }
  },
  "people": [
   {
    "id": "wren",
    "name": "Professor Thaddeus Wren",
    "role": "the absent-minded professor",
    "emoji": "🦉",
    "color": "#14b8a6"
   },
   {
    "id": "vera",
    "name": "Vera Vantablack",
    "role": "the veiled widow",
    "emoji": "🕷️",
    "color": "#8b5cf6"
   },
   {
    "id": "ash",
    "name": "Colonel Ash Redwood",
    "role": "the retired colonel",
    "emoji": "🎖️",
    "color": "#ef4444"
   },
   {
    "id": "prudence",
    "name": "Lady Prudence Opaline",
    "role": "the jewel heiress",
    "emoji": "💍",
    "color": "#f59e0b"
   },
   {
    "id": "coco",
    "name": "Mademoiselle Coco Lark",
    "role": "the cabaret singer",
    "emoji": "🎤",
    "color": "#ec4899"
   },
   {
    "id": "felix",
    "name": "Dr. Felix Grimm",
    "role": "the village physician",
    "emoji": "🩺",
    "color": "#10b981"
   },
   {
    "id": "v_locke",
    "name": "Curator Maximilian Locke",
    "role": "the museum curator",
    "emoji": "🗝️",
    "isVictim": true,
    "color": "#94a3b8"
   }
  ],
  "clues": [
   {
    "owner": "prudence",
    "kind": "dir_of_person",
    "other": "coco",
    "dir": "south"
   },
   {
    "owner": "felix",
    "kind": "dir_of_person",
    "other": "wren",
    "dir": "south"
   },
   {
    "owner": "wren",
    "kind": "dir_of_object",
    "objType": "sarcophagus",
    "dir": "west"
   },
   {
    "owner": "v_locke",
    "kind": "dir_of_object",
    "objType": "candelabrum",
    "dir": "east"
   },
   {
    "owner": "ash",
    "kind": "in_room",
    "room": 4
   },
   {
    "owner": "v_locke",
    "kind": "dir_of_person",
    "other": "vera",
    "dir": "north"
   },
   {
    "owner": "coco",
    "kind": "dir_of_person",
    "other": "v_locke",
    "dir": "east"
   },
   {
    "owner": "v_locke",
    "kind": "dir_of_object",
    "objType": "sarcophagus",
    "dir": "south"
   },
   {
    "owner": "wren",
    "kind": "dir_of_object",
    "objType": "statue",
    "dir": "east"
   },
   {
    "owner": "vera",
    "kind": "dir_of_person",
    "other": "felix",
    "dir": "east"
   },
   {
    "owner": "felix",
    "kind": "same_room_person",
    "other": "coco"
   },
   {
    "owner": "coco",
    "kind": "dir_of_object",
    "objType": "candelabrum",
    "dir": "north"
   }
  ],
  "givens": {},
  "story": {
   "title": "Midnight at the Meridian Museum",
   "intro": "Curator Maximilian Locke stayed late to authenticate a golden scarab. The scarab was real; the alibis were not. Six after-hours guests were locked in with him.",
   "reveal": "Case closed, exhibit opened. {murderer} had been selling forgeries through the gift shop for years — Locke’s authentication ledger was the loose thread you just pulled."
  },
  "theme": {
   "objectNames": {
    "bookshelf": {
     "label": "bookshelf",
     "plural": "bookshelves",
     "emoji": "📚"
    },
    "plant": {
     "label": "potted plant",
     "plural": "potted plants",
     "emoji": "🪴"
    },
    "candelabrum": {
     "label": "candelabrum",
     "plural": "candelabra",
     "emoji": "🕯️"
    },
    "armchair": {
     "label": "armchair",
     "plural": "armchairs",
     "emoji": "🛋️"
    },
    "clock": {
     "label": "grandfather clock",
     "plural": "grandfather clocks",
     "emoji": "🕰️"
    },
    "piano": {
     "label": "piano",
     "plural": "pianos",
     "emoji": "🎹"
    },
    "oven": {
     "label": "oven",
     "plural": "ovens",
     "emoji": "🔥"
    },
    "sack": {
     "label": "flour sack",
     "plural": "flour sacks",
     "emoji": "🌾"
    },
    "cake": {
     "label": "wedding cake",
     "plural": "wedding cakes",
     "emoji": "🎂"
    },
    "telescope": {
     "label": "telescope",
     "plural": "telescopes",
     "emoji": "🔭"
    },
    "globe": {
     "label": "star globe",
     "plural": "star globes",
     "emoji": "🌐"
    },
    "desk": {
     "label": "writing desk",
     "plural": "writing desks",
     "emoji": "🪑"
    },
    "slot": {
     "label": "slot machine",
     "plural": "slot machines",
     "emoji": "🎰"
    },
    "cards": {
     "label": "card table",
     "plural": "card tables",
     "emoji": "🃏"
    },
    "vault": {
     "label": "vault door",
     "plural": "vault doors",
     "emoji": "🔒"
    },
    "harp": {
     "label": "harp",
     "plural": "harps",
     "emoji": "🎻"
    },
    "curtain": {
     "label": "velvet curtain",
     "plural": "velvet curtains",
     "emoji": "🎭"
    },
    "chandelier": {
     "label": "fallen chandelier",
     "plural": "fallen chandeliers",
     "emoji": "💎"
    },
    "crate": {
     "label": "cargo crate",
     "plural": "cargo crates",
     "emoji": "📦"
    },
    "lantern": {
     "label": "storm lantern",
     "plural": "storm lanterns",
     "emoji": "🏮"
    },
    "wheel": {
     "label": "ship's wheel",
     "plural": "ship's wheels",
     "emoji": "☸️"
    },
    "fern": {
     "label": "giant fern",
     "plural": "giant ferns",
     "emoji": "🌿"
    },
    "fountain": {
     "label": "stone fountain",
     "plural": "stone fountains",
     "emoji": "⛲"
    },
    "beehive": {
     "label": "beehive",
     "plural": "beehives",
     "emoji": "🐝"
    },
    "statue": {
     "label": "marble statue",
     "plural": "marble statues",
     "emoji": "🗿"
    },
    "sarcophagus": {
     "label": "sarcophagus",
     "plural": "sarcophagi",
     "emoji": "⚱️"
    },
    "display": {
     "label": "display case",
     "plural": "display cases",
     "emoji": "🏺"
    }
   }
  },
  "solution": {
   "v_locke": 40,
   "wren": 1,
   "ash": 23,
   "coco": 20,
   "vera": 46,
   "prudence": 28,
   "felix": 10
  },
  "murderer": "vera",
  "difficulty": "hard"
 }
];
