// Generates the campaign cases from their briefs, verifies every guarantee,
// and freezes them into js/cases-data.js. Run: node scripts/build-cases.mjs

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { generateCase } from '../js/engine/generator.js';
import { countSolutions, logicSolve, murdererOfSolution } from '../js/engine/solver.js';
import { THEMES, CAMPAIGN_BRIEFS, pickTroupe } from '../js/roster.js';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

const cases = [];
for (const brief of CAMPAIGN_BRIEFS) {
  const people = [...pickTroupe(brief.suspects), brief.victim];
  if (people.length !== brief.size) {
    throw new Error(`${brief.id}: ${people.length} people for size ${brief.size}`);
  }
  const started = Date.now();
  const cse = generateCase({
    id: brief.id,
    seed: brief.seed,
    size: brief.size,
    theme: THEMES[brief.theme],
    people,
    story: brief.story,
    difficulty: brief.difficulty,
  });
  if (!cse) throw new Error(`${brief.id}: generation failed`);

  // Re-verify everything on the frozen artifact.
  const sols = countSolutions(cse, { limit: 3 });
  if (sols.length !== 1) throw new Error(`${brief.id}: ${sols.length} solutions`);
  if (!logicSolve(cse).solved) throw new Error(`${brief.id}: needs guessing`);
  const murderer = murdererOfSolution(cse);
  if (murderer !== cse.murderer) throw new Error(`${brief.id}: murderer mismatch`);

  cse.difficulty = brief.difficulty;
  cases.push(cse);
  console.log(
    `${brief.id} ok: ${brief.size}x${brief.size} ${brief.theme}, ${cse.clues.length} clues, ` +
    `murderer=${murderer}, ${Date.now() - started}ms`,
  );
}

const banner = '// AUTO-GENERATED by scripts/build-cases.mjs — every case verified to have\n' +
  '// exactly one solution and to be solvable without guessing. Do not hand-edit.\n';
writeFileSync(
  join(root, 'js', 'cases-data.js'),
  `${banner}export const CAMPAIGN_CASES = ${JSON.stringify(cases, null, 1)};\n`,
);
console.log(`\nFroze ${cases.length} cases into js/cases-data.js`);
